from typing import Any, Optional
from uuid import UUID

from sqlalchemy.orm import Session

from app.models.security_event import SecurityEvent


class SecurityEventService:
    """Persists security-related events generated by the RAG pipeline."""

    @staticmethod
    def record_event(
        db: Session,
        *,
        event_type: str,
        severity: str,
        pipeline_mode: str,
        trigger_payload: str,
        detection_mechanism: str,
        mitigation_action: str,
        user_id: Optional[UUID] = None,
        details: Optional[dict[str, Any]] = None,
    ) -> SecurityEvent:
        """Create and persist a security event."""
        event = SecurityEvent(
            event_type=event_type,
            severity=severity,
            user_id=user_id,
            pipeline_mode=pipeline_mode,
            trigger_payload=trigger_payload,
            detection_mechanism=detection_mechanism,
            mitigation_action=mitigation_action,
            details=details,
        )

        db.add(event)
        db.flush()

        return event